<?php
/*
* Butr Universal Travel Reservations
* A bleeding edge business management system for the travel industry.
*
* Copyright (C) 2012 Whalebone Studios and contributors.
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

// Sort Order
define('Butr\SORT_DIRECTION_ASCENDING', 'ascending');
define('Butr\SORT_DIRECTION_DESCENDING', 'descending');

// Sort Ordinal
define('Butr\SORT_ORDINAL_COUNTRY_DISPLAY_NAME', 'country_display_name');
define('Butr\SORT_ORDINAL_COUNTRY_NAME', 'country_name');
define('Butr\SORT_ORDINAL_DEFAULT', 'default');
define('Butr\SORT_ORDINAL_DISPLAY_LABEL', 'display_label');
define('Butr\SORT_ORDINAL_DOCK_ITEM_NAME', 'dock_item_name');
define('Butr\SORT_ORDINAL_DOCK_NAME', 'dock_name');
define('Butr\SORT_ORDINAL_FIRST_NAME', 'first_name');
define('Butr\SORT_ORDINAL_ITEM_NAME', 'item_name');
define('Butr\SORT_ORDINAL_LAST_NAME', 'last_name');
define('Butr\SORT_ORDINAL_MESSAGE_NAME', 'message_name');
define('Butr\SORT_ORDINAL_MODULE_NAME', 'module_name');
define('Butr\SORT_ORDINAL_NAME_LABEL', 'name_label');
define('Butr\SORT_ORDINAL_SECURITY_CLIENT_TYPE_LABEL', 'security_client_type_label');
define('Butr\SORT_ORDINAL_SUBITEM_NAME', 'subitem_name');
define('Butr\SORT_ORDINAL_SYSTEM_DOCK_TYPE_LABEL', 'system_dock_type_label');
define('Butr\SORT_ORDINAL_TAB_NAME', 'tab_name');
define('Butr\SORT_ORDINAL_TITLE_LABEL', 'title_label');
define('Butr\SORT_ORDINAL_UUID', 'uuid');
define('Butr\SORT_ORDINAL_IS_ACTIVE', 'is_active');

// Message Result
define('Butr\MESSAGE_RESULT_OK', 'OK');
define('Butr\MESSAGE_RESULT_WARNING', 'WARNING');
define('Butr\MESSAGE_RESULT_ERROR', 'ERROR');
define('Butr\MESSAGE_RESULT_EXPIRED', 'EXPIRED');

// Pagination Type
define('Butr\PAGINATION_TYPE_PAGE', 'page');
define('Butr\PAGINATION_TYPE_HELP', 'help');

// List Defaults
define('Butr\DEFAULT_LIST_SIZE', 20);
define('Butr\LIST_SIZE_ALL', -1);